In [1]:
def feat2image(x, target_size=(128,128)): 
    "This idea comes from MetNet"
    x = x.transpose(1,2)
    
    return x.unsqueeze(-1).unsqueeze(-1) * x.new_ones(1,1,1,*target_size)

In [15]:
import torch
target_size=(128,128)
x = torch.rand(1,1,3)
x = x.transpose(1,2)
    
x=x.unsqueeze(-1).unsqueeze(-1)  
print(f"x:{x.shape}")

x_ones=x.new_ones(1,1,1,*target_size)
print(f"x_ones:{x_ones.shape}")
feat2image(x, target_size=(4,4)) 

x:torch.Size([1, 3, 1, 1, 1])
x_ones:torch.Size([1, 1, 1, 128, 128])


tensor([[[[[[[0.6650, 0.6650, 0.6650, 0.6650],
             [0.6650, 0.6650, 0.6650, 0.6650],
             [0.6650, 0.6650, 0.6650, 0.6650],
             [0.6650, 0.6650, 0.6650, 0.6650]]]],



          [[[[0.4664, 0.4664, 0.4664, 0.4664],
             [0.4664, 0.4664, 0.4664, 0.4664],
             [0.4664, 0.4664, 0.4664, 0.4664],
             [0.4664, 0.4664, 0.4664, 0.4664]]]],



          [[[[0.8795, 0.8795, 0.8795, 0.8795],
             [0.8795, 0.8795, 0.8795, 0.8795],
             [0.8795, 0.8795, 0.8795, 0.8795],
             [0.8795, 0.8795, 0.8795, 0.8795]]]]]]])

In [29]:
import datetime
import numpy as np
batch_size=1
spatial_dim=4
# Time of the sample.
sample_time = [datetime.datetime(2020, 3, 1, 12, 0, 0)] * batch_size
# print(f"sample_time:{sample_time}")
# Timedelta to predict.
td = np.array([60] * batch_size)  # In minutes
sample_time = np.array([[x.hour, x.day, x.month] for x in sample_time],
                        dtype=np.float16)
print(f"sample_time:{sample_time.shape}")#(10, 3)

sample_time = np.reshape(sample_time, [batch_size, 1, 1, 1, 3])
print(f"sample_time:{sample_time.shape},{sample_time}") #(10, 1, 1, 1, 3)

sample_time = np.tile(sample_time, [1, 1, spatial_dim, spatial_dim, 1])
print(f"sample_time:{sample_time.shape},{sample_time}") #(10, 1, 4, 4, 3)



sample_time:(1, 3)
sample_time:(1, 1, 1, 1, 3),[[[[[12.  1.  3.]]]]]
sample_time:(1, 1, 4, 4, 3),[[[[[12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]]

   [[12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]]

   [[12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]]

   [[12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]
    [12.  1.  3.]]]]]


In [31]:
td=60
target_index=td // 2 - 1
np.stack([target_index, target_index], axis=-1)

array([29, 29])

In [38]:
def onehot_range(labels, num_classes, on_value=1.0, off_value=0.0):
  """Onehot but instead of a single 1, multiple 1's in a range is returned.

  Similar to common_utils.onehot but instead of 0...010...0, it returns
  0...01...10...0 where the provided range is inclusive for both beginning and
  end.

  Args:
    labels: ndarray-like, shape=(..., 2)
    num_classes: Number of classes.
    on_value: The value to use in the range.
    off_value: The value to use outside the range.

  Returns:
    ndarray-like, shape=(..., num_classes)
  """
  x0 = (labels[..., 0, None] <= np.arange(num_classes)[None])
  x1 = (labels[..., 1, None] >= np.arange(num_classes)[None])
  print("x0", x0)
  print("x0", x0)
  
  
  x = x0 & x1
  print("x", x)
  x = np.select(x, np.full(x.shape, on_value), np.full(x.shape, off_value))
  return x.astype(np.float32)
onehot_range(np.array([5,5]),20).shape

x0 [[False False False False False  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True]]
x0 [[False False False False False  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True]]
x [[False False False False False  True False False False False False False
  False False False False False False False False]]


(1, 20)